### ISSUE TITLE
pro.chain.wallet相关的包能够提供下么

### ISSUE THREAD

**Issue by AIYP1226** [ProChain/ProSDKEOS#3]
你好，最近在测试这个SDK，编译的时候没有pro.chain相关的包，这个怎么弄？求指教！

**Comment by oday0311** [comment]
那个是业务相关的， 你可以用你们自己的数据或者函数替换掉就可以了

**Comment by AIYP1226** [comment]
主要是我不是搞安卓的，公司也是用H5做的钱包，所以没法搞，这个就打扰了

**Comment by oday0311** [comment]
h5 做钱包有很大的安全隐患，手机钱包建议不要用h5方式做
